encoding: utf-8

title: Henry Ding
description: Henry Ding's Personal Website 
keywords: TMaize,Blog,Java,Html,JavaScript
author: Tong (Henry) Ding

permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

domainUrl: 'https://github.com/HHenryD/henryding.github.io'
baseurl: ''

menu:
  - title: Homepage
    url: /
  - title: Research
    url: /pages/research.html
  - title: CV
    url: /pages/cv.html


extClickEffect: true

extAdsense: false

extMath: false


theme: jekyll-theme-slate